# Generated by Django 5.2.8 on 2025-12-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_add_migrations',
            field=models.BooleanField(default=False, help_text='Can create migration projects and switch migrations'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_delete_migrations',
            field=models.BooleanField(default=False, help_text='Can delete migration projects'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_edit_migrations',
            field=models.BooleanField(default=False, help_text='Can edit migration projects and switch migrations'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_export_migration_reports',
            field=models.BooleanField(default=False, help_text='Can export migration reports'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_issues',
            field=models.BooleanField(default=False, help_text='Can report and update migration issues'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_port_mappings',
            field=models.BooleanField(default=False, help_text='Can add/edit port mappings'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_user_impact',
            field=models.BooleanField(default=False, help_text='Can add/edit user impact assessments'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_update_migration_status',
            field=models.BooleanField(default=False, help_text='Can update migration status and progress'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_migrations',
            field=models.BooleanField(default=False, help_text='Can view migration dashboard and projects'),
        ),
    ]
