# Generated by Django 5.2.8 on 2025-12-16 08:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('switches', '0002_alter_switch_options_switch_building_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Planning', max_length=20)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_migrations', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_migrations', to=settings.AUTH_USER_MODEL)),
                ('team_members', models.ManyToManyField(blank=True, related_name='migration_team', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SwitchMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration_status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Pre-Check', 'Pre-Check Done'), ('In Progress', 'In Progress'), ('Testing', 'Testing'), ('Completed', 'Completed'), ('Rolled Back', 'Rolled Back'), ('Failed', 'Failed')], default='Scheduled', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('fiber_ports_to_migrate', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fiber_ports_migrated', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('utp_ports_to_migrate', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('utp_ports_migrated', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('scheduled_date', models.DateTimeField()),
                ('scheduled_downtime_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_downtime_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('pre_migration_notes', models.TextField(blank=True, help_text='Pre-migration checklist and notes')),
                ('migration_notes', models.TextField(blank=True, help_text='Notes during migration')),
                ('post_migration_notes', models.TextField(blank=True, help_text='Post-migration verification notes')),
                ('issues_encountered', models.TextField(blank=True)),
                ('rollback_plan', models.TextField(blank=True)),
                ('config_backup_done', models.BooleanField(default=False)),
                ('pre_check_done', models.BooleanField(default=False)),
                ('stakeholder_notified', models.BooleanField(default=False)),
                ('post_verification_done', models.BooleanField(default=False)),
                ('documentation_updated', models.BooleanField(default=False)),
                ('estimated_downtime', models.IntegerField(blank=True, help_text='Estimated downtime in minutes', null=True)),
                ('actual_downtime', models.IntegerField(blank=True, help_text='Actual downtime in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_migrations', to=settings.AUTH_USER_MODEL)),
                ('backup_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_migrations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_switch_migrations', to=settings.AUTH_USER_MODEL)),
                ('new_switch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migrations_as_new', to='switches.switch')),
                ('old_switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrations_as_old', to='switches.switch')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrations', to='migrations.migrationproject')),
            ],
            options={
                'ordering': ['scheduled_date'],
                'unique_together': {('project', 'old_switch')},
            },
        ),
        migrations.CreateModel(
            name='PortMigrationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_port_number', models.CharField(max_length=50)),
                ('old_port_type', models.CharField(choices=[('Fiber', 'Fiber'), ('UTP', 'UTP')], max_length=20)),
                ('old_port_description', models.CharField(blank=True, max_length=200)),
                ('old_vlan', models.CharField(blank=True, max_length=100)),
                ('new_port_number', models.CharField(blank=True, max_length=50)),
                ('new_port_type', models.CharField(choices=[('Fiber', 'Fiber'), ('UTP', 'UTP')], max_length=20)),
                ('new_vlan', models.CharField(blank=True, max_length=100)),
                ('connected_device', models.CharField(blank=True, help_text='Device connected to this port', max_length=200)),
                ('user_department', models.CharField(blank=True, max_length=100)),
                ('user_contact', models.CharField(blank=True, max_length=100)),
                ('is_migrated', models.BooleanField(default=False)),
                ('migration_date', models.DateTimeField(blank=True, null=True)),
                ('is_tested', models.BooleanField(default=False)),
                ('test_result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('test_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('migrated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('switch_migration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_mappings', to='migrations.switchmigration')),
            ],
            options={
                'ordering': ['old_port_number'],
            },
        ),
        migrations.CreateModel(
            name='MigrationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL)),
                ('switch_migration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='migrations.switchmigration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrationChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('Pre-Migration', 'Pre-Migration'), ('During Migration', 'During Migration'), ('Post-Migration', 'Post-Migration')], max_length=20)),
                ('item_order', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=300)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('switch_migration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='migrations.switchmigration')),
            ],
            options={
                'ordering': ['phase', 'item_order'],
            },
        ),
        migrations.CreateModel(
            name='MigrationActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('switch_migration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='migrations.switchmigration')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserImpactAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('number_of_users_affected', models.IntegerField(default=0)),
                ('critical_services', models.TextField(blank=True, help_text='List critical services affected')),
                ('notified', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgment_received', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
                ('issues_reported', models.TextField(blank=True)),
                ('satisfaction_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('switch_migration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_impacts', to='migrations.switchmigration')),
            ],
            options={
                'ordering': ['department_name'],
            },
        ),
    ]
