# Generated by Django 5.2.8 on 2025-12-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('is_stack', models.BooleanField(default=False)),
                ('stack_priority', models.IntegerField(default=1, help_text='Stack member priority (1=master)')),
                ('stack_member_number', models.IntegerField(default=1, help_text='Member number in stack')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('deleted_by', models.CharField(blank=True, help_text='User who deleted', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['hostname', 'stack_priority', 'stack_member_number'],
            },
        ),
    ]
