# Generated by Django 5.2.8 on 2025-12-10 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='switch',
            options={'ordering': ['building_no', 'hostname', 'stack_member_number'], 'verbose_name': 'Switch', 'verbose_name_plural': 'Switches'},
        ),
        migrations.AddField(
            model_name='switch',
            name='building_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Building No'),
        ),
        migrations.AddField(
            model_name='switch',
            name='cabinet_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cabinet No'),
        ),
        migrations.AddField(
            model_name='switch',
            name='cabinet_tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cabinet Tag'),
        ),
        migrations.AddField(
            model_name='switch',
            name='communication_room_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Communication Room No'),
        ),
        migrations.AddField(
            model_name='switch',
            name='it_tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='IT Tag'),
        ),
        migrations.AddField(
            model_name='switch',
            name='no_of_line_cards_fiber',
            field=models.IntegerField(default=0, verbose_name='Line Cards (Fiber)'),
        ),
        migrations.AddField(
            model_name='switch',
            name='no_of_line_cards_utp',
            field=models.IntegerField(default=0, verbose_name='Line Cards (UTP)'),
        ),
        migrations.AddField(
            model_name='switch',
            name='no_of_power_supplies',
            field=models.IntegerField(default=0, verbose_name='No. of Power Supplies'),
        ),
        migrations.AddField(
            model_name='switch',
            name='no_of_used_ports',
            field=models.IntegerField(default=0, verbose_name='No. of Used Ports'),
        ),
        migrations.AddField(
            model_name='switch',
            name='port_type',
            field=models.CharField(blank=True, choices=[('24P', '24 Port'), ('48P', '48 Port'), ('Other', 'Other')], max_length=10, verbose_name='24P or 48P'),
        ),
        migrations.AddField(
            model_name='switch',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='switch',
            name='switch_role',
            field=models.CharField(blank=True, choices=[('core', 'Core'), ('distribution', 'Distribution'), ('access', 'Access'), ('other', 'Other')], max_length=20, verbose_name='Switch Role'),
        ),
        migrations.AddField(
            model_name='switch',
            name='total_ports_fiber',
            field=models.IntegerField(default=0, verbose_name='Total Ports (Fiber)'),
        ),
        migrations.AddField(
            model_name='switch',
            name='total_ports_utp',
            field=models.IntegerField(default=0, verbose_name='Total Ports (UTP)'),
        ),
        migrations.AddField(
            model_name='switch',
            name='used_power_supplies',
            field=models.IntegerField(default=0, verbose_name='Used Power Supplies'),
        ),
        migrations.AddField(
            model_name='switch',
            name='vendor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='switch',
            name='hostname',
            field=models.CharField(max_length=100, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='is_stack',
            field=models.BooleanField(default=False, verbose_name='Is Stack'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='stack_member_number',
            field=models.IntegerField(default=1, verbose_name='Stack Member Number'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='stack_priority',
            field=models.IntegerField(default=1, verbose_name='Stack Priority'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Maintenance', 'Maintenance'), ('EoL', 'End of Life')], default='Active', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='ColumnPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_columns', models.JSONField(default=list, help_text='List of visible column names')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='column_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Column Preference',
                'verbose_name_plural': 'Column Preferences',
            },
        ),
    ]
